//Author:Riyasat Ali 
// http://www.riytechnologies.com:
//Linkedin: https://www.linkedin.com/in/riyasat-ali/
using System;
using System.Collections.Generic;
using System.Text;

namespace LinqToQueryExtensions.Utilities.Attributes
{
	public class IdentityAttribute : Attribute
	{
		public bool AutoGenerated { get; set; }
	}
}
