using System;
using System.Collections.Generic;
using System.Text;

namespace LinqToQueryExtensions.Utilities.Attributes
{
	public class IdentityAttribute : Attribute
	{
		public bool AutoGenerated { get; set; }
	}
}
