using System.ComponentModel.DataAnnotations.Schema;
using LinqToQueryExtensions.Utilities.Attributes;

namespace LinqToQueryExample.Entities
{
	public class Product
	{
		[Identity(AutoGenerated = true)]
		public int Id { get; set; }
		public string ProductName { get; set; }
		[ForeignKey("SupplierId")]
		public int SupplierId { get; set; }
		public string UnitPrice { get; set; }
		public string Package { get; set; }
		public string IsDiscontinued { get; set; }
		public Supplier SupplierInfo { get; set; }
	}


}
