using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LinqToQueryExtensions.Utilities.Attributes;

namespace LinqToQueryExample.Entities
{
	[Table("Supplier")]
	public class Supplier
	{
		[Identity(AutoGenerated = true)]
		[Column("Id")]
		public int Id { get; set; }
		[Required]
		public string CompanyName { get; set; }
		public string ContactName { get; set; }
		public string ContactTitle { get; set; }
		public string City { get; set; }
		public string Country { get; set; }
		public string Phone { get; set; }
		public string Fax { get; set; }
		[Ignore]
		public IList<Product> Products { get; set; }
		[Ignore]
		public OrderItem Order { get; set; }
	}
}
